version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authdb
    ports:
      - "3306:3306"
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expensedb
    ports:
      - "5432:5432"
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - rabbitmq
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka-server
      - config-server
  expense-service:
    build: ./expense-service
    ports:
      - "8082:8082"
    depends_on:
      - postgresql
      - rabbitmq
      - eureka-server
      - config-server
  category-service:
    build: ./category-service
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
      - rabbitmq
      - eureka-server
      - config-server